# Generated by Django 4.0.5 on 2022-06-12 17:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('article_title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=10000)),
                ('username', models.CharField(default='', max_length=100)),
                ('article_image', models.CharField(default='', max_length=200)),
                ('company', models.CharField(default='', max_length=100)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
