# Generated by Django 4.0.5 on 2022-06-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='/media/empty.png', null=True, upload_to='None'),
        ),
    ]
